project_name: "go-emojify"
build:
  binary: "go-emojify"
  main: cmd/go-emojify/main.go
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - windows
    - darwin
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  ignore:
    - goos: windows
      goarch: arm
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_{{ .Tag }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^img:"
release:
  draft: true
  prerelease: auto
brews:
  - tap:
      owner: yusukebe
      name: homebrew-go-emojify
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: "https://github.com/yusukebe/go-emojify"
    description: "Yet another emojify command written in Go "
    license: "MIT"
